!Config
items:
- !ConfigItem
  delta: 0
  entities:
  - session1
  - D:/Temp/
  - C:/Users/Grandbox/Downloads
- !ConfigItem
  delta: 1
  entities:
  - daily1
- !ConfigItem
  delta: 7
  entities:
  - weekly1
- !ConfigItem
  delta: 30
  entities:
  - monthly1
